name: WARP Plus Key Generator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate WARP Key
        run: |
          python3 -c '
          import urllib.request
          import json
          import datetime
          import random
          import string

          def gen_string(length):
              return "".join(random.choice(string.ascii_letters + string.digits) for _ in range(length))

          url = "https://api.cloudflareclient.com/v0a1925/reg"
          body = {"install_id": gen_string(22), "fcm_token": f"{gen_string(22)}:APA91b{gen_string(134)}", "tos": datetime.datetime.now().isoformat()[:-3] + "+07:00", "model": "Android", "type": "Android", "locale": "en_US"}
          data = json.dumps(body).encode("utf-8")
          headers = {"Content-Type": "application/json; charset=UTF-8", "User-Agent": "okhttp/3.12.1"}
          req = urllib.request.Request(url, data=data, headers=headers)
          res = urllib.request.urlopen(req)
          res_json = json.loads(res.read().decode("utf-8"))
          key = res_json["account"]["license"]
          print("\n" + "="*40)
          print("SUCCESS! YOUR WARP+ KEY IS:")
          print(key)
          print("="*40 + "\n")
          '
